### ISSUE TITLE
Improve app support -> Implement YNH level 4 (up to 7) guidelines

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/codimd_ynh#14]
Global issue to track what needs to be done to improve this app, and make it a fully fledged standard Yunohost app.
Forum topic: https://forum.yunohost.org/t/codimd-hackmd-fork-official-topic/11110

To be done (in an approximate order of priority, but any contribution is warmly welcome !):
- [x] Install and removal (level 2): #11 and #19 fixed this, thanks to @alexAubin and @Lab-8916100448256  ! :tada:.
Still some tests to be done on various configurations…
- [x] Improve install robustness, we should at least look into --line-match for systemd_action to check if service started, otherwise test on the CI may fail because of 502 errors
- [x] Upgrade working (level 3) #22 
- [x] Backup&Restore working (level 4) #21 
- [x] Set app status to "working" in YNH `community.json` https://github.com/YunoHost/apps/pull/914
- [x] Handle non domain root install #24 
- [x] Level 5 specs
- [x] In Yunohost-Apps repository (Level 6)
- [x] Level 7 specs

**Comment by ericgaspar** [comment]
Level 7 reached. Closing issue
